#!/usr/bin/env python

from movie_tracker import tracker
import sys

if __name__ == '__main__':
    # run the project code here
    movieTitle = sys.argv[1]
    try:
        movieYear = sys.argv[2]
    except IndexError:
        movieYear =  None

    trackerPod = tracker.MovieReview(movieTitle, movieYear)
    trackerPod.getMovie()